import {
  User,
  Customer,
  Courier,
  Delivery,
  Activity,
  DashboardKPI,
  DeliveryStats,
  CourierPerformance,
} from '@/types';

// Mock User
export const mockUser: User = {
  id: 'user-001',
  email: 'admin@pilefacelogistics.mg',
  name: 'Jean Rakoto',
  role: 'super_admin',
  avatar: 'https://api.dicebear.com/7.x/avataaars/svg?seed=Jean',
};

// Mock Customers
export const mockCustomers: Customer[] = [
  {
    id: 'cust-001',
    fullName: 'Rakoto Jean',
    companyName: 'Rakoto Trading',
    email: 'rakoto@trading.mg',
    phoneNumber: '+261 32 123 4567',
    address: 'Rue de la Paix, Antananarivo',
    registrationDate: '2024-01-15',
    totalDeliveries: 45,
    averageRating: 4.8,
  },
  {
    id: 'cust-002',
    fullName: 'Marie Andrianampoinimerina',
    companyName: 'Andriana Boutique',
    email: 'marie@boutique.mg',
    phoneNumber: '+261 33 234 5678',
    address: 'Avenue de l\'Indépendance, Antananarivo',
    registrationDate: '2024-02-20',
    totalDeliveries: 28,
    averageRating: 4.6,
  },
  {
    id: 'cust-003',
    fullName: 'Pierre Razafindrakoto',
    companyName: 'Razafindra Import Export',
    email: 'pierre@razafindra.mg',
    phoneNumber: '+261 34 345 6789',
    address: 'Rue Colbert, Antananarivo',
    registrationDate: '2024-03-10',
    totalDeliveries: 62,
    averageRating: 4.9,
  },
  {
    id: 'cust-004',
    fullName: 'Sophie Randrianasolo',
    companyName: 'Randriana Consulting',
    email: 'sophie@randriana.mg',
    phoneNumber: '+261 32 456 7890',
    address: 'Boulevard de la Liberté, Antananarivo',
    registrationDate: '2024-04-05',
    totalDeliveries: 15,
    averageRating: 4.7,
  },
  {
    id: 'cust-005',
    fullName: 'Luc Rakotondravony',
    companyName: 'Rakotondra Logistics',
    email: 'luc@rakotondra.mg',
    phoneNumber: '+261 33 567 8901',
    address: 'Avenue Joffre, Antananarivo',
    registrationDate: '2024-05-12',
    totalDeliveries: 38,
    averageRating: 4.5,
  },
];

// Mock Couriers
export const mockCouriers: Courier[] = [
  {
    id: 'courier-001',
    fullName: 'Andry Razafindraibe',
    phoneNumber: '+261 32 111 2222',
    nationalId: '101-234567-8',
    assignedZone: 'Antananarivo Central',
    status: 'available',
    totalDeliveries: 156,
    successRate: 98.5,
    averageDeliveryTime: 45,
    punctualityRate: 96.2,
    currentLocation: { lat: -18.8792, lng: 47.5079 },
    avatar: 'https://api.dicebear.com/7.x/avataaars/svg?seed=Andry',
  },
  {
    id: 'courier-002',
    fullName: 'Hery Rakotoarison',
    phoneNumber: '+261 33 222 3333',
    nationalId: '102-345678-9',
    assignedZone: 'Antananarivo North',
    status: 'busy',
    totalDeliveries: 142,
    successRate: 97.8,
    averageDeliveryTime: 52,
    punctualityRate: 94.1,
    currentLocation: { lat: -18.8500, lng: 47.5200 },
    avatar: 'https://api.dicebear.com/7.x/avataaars/svg?seed=Hery',
  },
  {
    id: 'courier-003',
    fullName: 'Nadia Rasolofo',
    phoneNumber: '+261 34 333 4444',
    nationalId: '103-456789-0',
    assignedZone: 'Antananarivo South',
    status: 'available',
    totalDeliveries: 168,
    successRate: 99.1,
    averageDeliveryTime: 40,
    punctualityRate: 98.5,
    currentLocation: { lat: -18.9000, lng: 47.5100 },
    avatar: 'https://api.dicebear.com/7.x/avataaars/svg?seed=Nadia',
  },
  {
    id: 'courier-004',
    fullName: 'Toby Razakamampionona',
    phoneNumber: '+261 32 444 5555',
    nationalId: '104-567890-1',
    assignedZone: 'Antananarivo East',
    status: 'offline',
    totalDeliveries: 134,
    successRate: 96.5,
    averageDeliveryTime: 48,
    punctualityRate: 92.3,
    avatar: 'https://api.dicebear.com/7.x/avataaars/svg?seed=Toby',
  },
  {
    id: 'courier-005',
    fullName: 'Rina Rakotomanga',
    phoneNumber: '+261 33 555 6666',
    nationalId: '105-678901-2',
    assignedZone: 'Antananarivo West',
    status: 'available',
    totalDeliveries: 151,
    successRate: 98.2,
    averageDeliveryTime: 44,
    punctualityRate: 95.8,
    currentLocation: { lat: -18.8700, lng: 47.4900 },
    avatar: 'https://api.dicebear.com/7.x/avataaars/svg?seed=Rina',
  },
];

// Mock Deliveries
export const mockDeliveries: Delivery[] = [
  {
    id: 'deliv-001',
    trackingNumber: 'PFC-2024-001',
    sender: mockCustomers[0],
    receiver: mockCustomers[1],
    pickupAddress: 'Rue de la Paix, Antananarivo',
    deliveryAddress: 'Avenue de l\'Indépendance, Antananarivo',
    packageType: 'Documents',
    deliveryType: 'Standard',
    priority: 'normal',
    status: 'delivered',
    assignedCourier: mockCouriers[0],
    deliveryDate: '2024-06-18',
    estimatedDeliveryTime: '14:00',
    actualDeliveryTime: '13:45',
  },
  {
    id: 'deliv-002',
    trackingNumber: 'PFC-2024-002',
    sender: mockCustomers[2],
    receiver: mockCustomers[3],
    pickupAddress: 'Rue Colbert, Antananarivo',
    deliveryAddress: 'Boulevard de la Liberté, Antananarivo',
    packageType: 'Parcels',
    deliveryType: 'Express',
    priority: 'urgent',
    status: 'in_transit',
    assignedCourier: mockCouriers[1],
    deliveryDate: '2024-06-18',
    estimatedDeliveryTime: '15:30',
  },
  {
    id: 'deliv-003',
    trackingNumber: 'PFC-2024-003',
    sender: mockCustomers[1],
    receiver: mockCustomers[4],
    pickupAddress: 'Avenue de l\'Indépendance, Antananarivo',
    deliveryAddress: 'Avenue Joffre, Antananarivo',
    packageType: 'Electronics',
    deliveryType: 'Standard',
    priority: 'express',
    status: 'picked_up',
    assignedCourier: mockCouriers[2],
    deliveryDate: '2024-06-18',
    estimatedDeliveryTime: '16:00',
  },
  {
    id: 'deliv-004',
    trackingNumber: 'PFC-2024-004',
    sender: mockCustomers[3],
    receiver: mockCustomers[0],
    pickupAddress: 'Boulevard de la Liberté, Antananarivo',
    deliveryAddress: 'Rue de la Paix, Antananarivo',
    packageType: 'Fragile Items',
    deliveryType: 'Standard',
    priority: 'normal',
    status: 'assigned',
    assignedCourier: mockCouriers[4],
    deliveryDate: '2024-06-18',
    estimatedDeliveryTime: '17:00',
  },
  {
    id: 'deliv-005',
    trackingNumber: 'PFC-2024-005',
    sender: mockCustomers[4],
    receiver: mockCustomers[2],
    pickupAddress: 'Avenue Joffre, Antananarivo',
    deliveryAddress: 'Rue Colbert, Antananarivo',
    packageType: 'Documents',
    deliveryType: 'Express',
    priority: 'confidential',
    status: 'pending',
    deliveryDate: '2024-06-19',
    estimatedDeliveryTime: '10:00',
  },
];

// Mock Dashboard KPI
export const mockDashboardKPI: DashboardKPI = {
  totalDeliveries: 1247,
  deliveriesToday: 34,
  pendingDeliveries: 8,
  completedDeliveries: 1156,
  activeCouriers: 3,
  availableCouriers: 4,
  totalCustomers: 127,
};

// Mock Activities
export const mockActivities: Activity[] = [
  {
    id: 'act-001',
    type: 'new_delivery',
    title: 'Nouvelle livraison créée',
    description: 'Livraison PFC-2024-005 créée par Rakoto Jean',
    timestamp: '2024-06-18T10:30:00Z',
    relatedId: 'deliv-005',
    icon: 'Package',
  },
  {
    id: 'act-002',
    type: 'completed_delivery',
    title: 'Livraison complétée',
    description: 'Livraison PFC-2024-001 livrée avec succès',
    timestamp: '2024-06-18T13:45:00Z',
    relatedId: 'deliv-001',
    icon: 'CheckCircle',
  },
  {
    id: 'act-003',
    type: 'courier_update',
    title: 'Mise à jour de coursier',
    description: 'Andry Razafindraibe est maintenant disponible',
    timestamp: '2024-06-18T14:00:00Z',
    relatedId: 'courier-001',
    icon: 'User',
  },
  {
    id: 'act-004',
    type: 'delayed_delivery',
    title: 'Livraison retardée',
    description: 'Livraison PFC-2024-002 retardée de 15 minutes',
    timestamp: '2024-06-18T15:15:00Z',
    relatedId: 'deliv-002',
    icon: 'AlertCircle',
  },
  {
    id: 'act-005',
    type: 'new_delivery',
    title: 'Nouvelle livraison créée',
    description: 'Livraison PFC-2024-006 créée par Marie Andrianampoinimerina',
    timestamp: '2024-06-18T15:45:00Z',
    relatedId: 'deliv-005',
    icon: 'Package',
  },
];

// Mock Delivery Statistics
export const mockDeliveryStats: DeliveryStats[] = [
  { date: '2024-06-12', count: 28, completed: 26, pending: 2, cancelled: 0 },
  { date: '2024-06-13', count: 31, completed: 30, pending: 1, cancelled: 0 },
  { date: '2024-06-14', count: 25, completed: 24, pending: 1, cancelled: 0 },
  { date: '2024-06-15', count: 35, completed: 33, pending: 2, cancelled: 0 },
  { date: '2024-06-16', count: 29, completed: 28, pending: 1, cancelled: 0 },
  { date: '2024-06-17', count: 32, completed: 31, pending: 1, cancelled: 0 },
  { date: '2024-06-18', count: 34, completed: 28, pending: 6, cancelled: 0 },
];

// Mock Courier Performance
export const mockCourierPerformance: CourierPerformance[] = mockCouriers.map((courier) => ({
  courierId: courier.id,
  courierName: courier.fullName,
  totalDeliveries: courier.totalDeliveries,
  successRate: courier.successRate,
  averageDeliveryTime: courier.averageDeliveryTime,
  punctualityRate: courier.punctualityRate,
  rating: 4.5 + Math.random() * 0.5,
}));

// Monthly delivery statistics
export const mockMonthlyStats = [
  { month: 'Jan', deliveries: 245, completed: 238, cancelled: 7 },
  { month: 'Feb', deliveries: 267, completed: 258, cancelled: 9 },
  { month: 'Mar', deliveries: 289, completed: 281, cancelled: 8 },
  { month: 'Apr', deliveries: 301, completed: 294, cancelled: 7 },
  { month: 'May', deliveries: 318, completed: 310, cancelled: 8 },
  { month: 'Jun', deliveries: 342, completed: 333, cancelled: 9 },
];

// Delivery status distribution
export const mockDeliveryStatusDistribution = [
  { status: 'Delivered', value: 1156, color: '#10B981' },
  { status: 'In Transit', value: 45, color: '#3B82F6' },
  { status: 'Pending', value: 32, color: '#F59E0B' },
  { status: 'Cancelled', value: 14, color: '#EF4444' },
];
